apiVersion: v1
kind: PersistentVolume
metadata:
  name: llms-pv
spec:
  storageClassName: "azure-blob-sc"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
      #readOnly: true
    volumeHandle: aksmodelsstorage-llms
    volumeAttributes:
      containerName: llms
      storageAccount: aksmodelsstorage
      protocol: fuse
      resourceGroup: IgniteStorage 
      authType: "ManagedIdentity"