apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llms-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: llms-pv
  storageClassName: "azure-blob-sc"