apiVersion: v1
kind: Service
metadata:
  name: ray-service
spec:
  type: NodePort
  selector:
    ray.io/group: headgroup
    ray.io/node-type: head
  ports:
    - name: http
      port: 8265
      targetPort: 8265
      nodePort: 30100
